# Generated by Django 5.1.7 on 2025-07-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipamentos', '0002_equipamento_setores'),
        ('Pecas', '0001_initial'),
        ('Tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.CharField(max_length=20, unique=True, verbose_name='Número da Ordem')),
                ('data_solicitacao', models.DateField(verbose_name='Data da Solicitação')),
                ('tipo', models.CharField(choices=[('Preventiva', 'Preventiva'), ('Corretiva', 'Corretiva')], max_length=10, verbose_name='Tipo')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluida', 'Concluída')], default='Pendente', max_length=12, verbose_name='Status')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_manutencao', to='Equipamentos.equipamento')),
                ('tecnico_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_manutencao', to='Tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Ordem de Manutenção',
                'verbose_name_plural': 'Ordens de Manutenção',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.CreateModel(
            name='PecasManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Unitário')),
                ('ordem_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='Manutencoes.ordemmanutencao')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pecas.peca')),
            ],
            options={
                'verbose_name': 'Peça de Manutenção',
                'verbose_name_plural': 'Peças de Manutenção',
                'unique_together': {('ordem_manutencao', 'peca')},
            },
        ),
    ]
