# Generated by Django 5.1.7 on 2025-07-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manutencoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecasmanutencao',
            name='custo_unitario',
        ),
        migrations.RemoveField(
            model_name='pecasmanutencao',
            name='quantidade',
        ),
    ]
