# Generated by Django 5.1.7 on 2025-08-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manutencoes', '0002_remove_pecasmanutencao_custo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemmanutencao',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data da Solicitação'),
        ),
        migrations.AlterField(
            model_name='ordemmanutencao',
            name='numero_ordem',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número da Ordem'),
        ),
    ]
