# Generated by Django 5.1.7 on 2025-07-15 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Setores', '0002_equipamentosetor'),
        ('Tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='setor',
            name='tecnico_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='setores_responsaveis', to='Tecnicos.tecnico'),
            preserve_default=False,
        ),
    ]
