# Generated by Django 5.2.1 on 2025-07-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_peca', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('estoque', models.IntegerField()),
                ('data_da_ultima_compra', models.DateField()),
            ],
        ),
    ]
